apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "luxcampus.fullname" . }}
spec:
  defaultBackend:
    service:
      name: {{ include "luxcampus.fullname" . }}
      port:
        number: {{ .Values.service.http.port }}
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
        - path: {{ .Values.ingress.path }}
          pathType: {{ .Values.ingress.pathType }}
          backend:
            service:
              name:  {{ include "luxcampus.fullname" . }}
              port:
                number: {{ .Values.service.http.port }}