apiVersion: v1
kind: Secret
metadata:
  name: {{ template "luxcampus.fullname" $ }}
  labels:
    {{- include "luxcampus.labels" $ | nindent 4 }}
type: Opaque
data:
{{- range $key,$value := .Values.environmentSecrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}