---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "luxcampus.fullname" . }}-registry
  labels:
    {{- include "luxcampus.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "luxcampus.imagePullSecret" . }}
