apiVersion: v1
kind: Service
metadata:
  name: {{ include "luxcampus.fullname" . }}
  labels:
    {{- include "luxcampus.labels" . | nindent 4 }}
    app.metrics: {{ .Values.product }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.http.port }}
      targetPort: http
      nodePort: 32000
      name: http
  selector:
    {{- include "luxcampus.selectorLabels" . | nindent 4 }}
    app.metrics: {{ .Values.product }}
